name: pizza-planet-ci

on:
  push:
    branches:
    - main
  
  pull_request:
    branches:
    - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Initiate Database
      run: |
        python3 manage.py db init
        python3 manage.py db migrate
        python3 manage.py db upgrade

    - name: Autoformatter with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive **/*.py

    - name: Lint with flake8
      run: |
        flake8 . --show-source --statistics

    - name: Run tests and collect coverage
      run: |
        python3 -m pytest -v --cov .

    - name: Upload coverage report to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov

    - name: Test coverage with Codecov
      uses: codecov/codecov-action@v3

    - run: echo "🍏 This job's status is ${{ job.status }}."
