name: pizza-planet-ci

on:
  push:
    branches:
    - "**"
  
  pull_request:
    branches:
    - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.10.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt

    - name: Initiate database
      run: |
        python3 manage.py db init
        python3 manage.py db migrate
        python3 manage.py db upgrade

    - name: Autoformatter with autopep8
      run: |
        autopep8 --in-place --aggressive --aggresive **/*.py

    - name: Lint with flake8
      run: |
        python3 manage.py test

    - run: echo "🍏 This job's status is ${{ job.status }}."
